### PR TITLE
feyza add pricing page

### PR DESCRIPTION
**Pull request by fyzaden**

### CODE REVIEW

**Review by annasvst — APPROVED** [review]
Well done Feyza! The stackoverflow page project was a hard one, actually but you did very good and I believe you learned a lot, too. 🙂💪

**Comment by annasvst** [comment]
I misunderstood it a bit, thought it's for stackoverflow page. I'm reviewing the code now and will come back with the feedback :)

**Review by annasvst — COMMENTED** [review]
Hi @fyzaden, you can see corrections and suggestions to Pricing page assignment in the Pull request here: https://github.com/frontend-from-0/091123-exercises/pull/15/files
This time I just added some minor fixes as a pull request instead of a normal code review, you can approve the pull request and merge it directly into your branch if you like.
Let me know if something is unclear in the changes :)

**Comment by fyzaden** [comment]
I will add  the stackoverflow page into lesson (I dont remember now :) ) files  when ı finied it . I work over the css in this page.

**Comment by fyzaden** [comment]
Thank you for your nice comment. I am determined to learn all the topics and will be a front-end developer for now (after that maybe Full stack dev :) ). Every day I dream of the day I get to work.

**Review by annasvst — APPROVED** [review]

**Pull request merged**
